### PR TITLE
Remove neovim from installation

### PR DESCRIPTION
**Pull request by MarcoDiFrancesco**
Is neovim package really needed in a clean setup when vim is already installed?

### CODE REVIEW

**Comment by as3ii** [comment]
> Is neovim package really needed in a clean setup when vim is already installed?

check the installed packages. The `base` package does not include vim or vi

**Comment by as3ii** [comment]
and talking about `networkmanager`: I don't want to configure networking in the first step of the installation process. The network manager should be inside the user configuration script, in this way anyone can choose his preferred network manager

**Comment by MarcoDiFrancesco** [comment]
Network manager is something I added for myself, I didn't mean to add it in this pull request and I'll remove it.
About `vim` I realized later that was not installed, what do you think about installing `vim` instead of `neovim`? How "personal" is this script?

**Comment by as3ii** [comment]
> What do you think about installing `vim` instead of `neovim`? How "personal" is this script?

neovim is fully compatible with vim, I don't see any reason to prefer vim. I could add an `ln -s /usr/bin/nvim /usr/bin/vim`, if you want. Or, if you explain your reasons, I could replace it with regular vim without any problem

**Comment by MarcoDiFrancesco** [comment]
It's just as a minimalistic approach because I tought `vim` package was a dependency of `neovim`. Because it's not can make sense not to have it installed.

**Pull request closed without merging**
